Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Controllers/EditController.cs
using System.Linq;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Data;

namespace WebApplication2.Controllers
{
    public class EditController : Controller
    {
        private readonly DatabaseContext _context;

        public EditController()
        {
            _context = new DatabaseContext();
        }

        // GET: Edit/Index
        public ActionResult Index()
        {
            // Check if the user is logged in by checking the session
            var userId = Session["UserId"];
            if (userId == null)
            {
                return RedirectToAction("Login", "Authentication"); // Redirect to login if not logged in
            }

            var user = _context.Users.FirstOrDefault(u => u.Id == (int)userId);
            if (user == null)
            {
                return HttpNotFound(); // If no user found, return 404
            }

            return View(user); // Pass the user data to the view
        }

        // POST: Edit/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Users user)
        {
            if (ModelState.IsValid)
            {
                // Check if the user is logged in by checking the session
                var userId = Session["UserId"];
                if (userId == null)
                {
                    return RedirectToAction("Login", "Authentication"); // Redirect to login if not logged in
                }

                // Retrieve the existing user from the database
                var existingUser = _context.Users.FirstOrDefault(u => u.Id == (int)userId);
                if (existingUser == null)
                {
                    return HttpNotFound(); // If no user found, return 404
                }

                // Update the user details
                existingUser.FirstName = user.FirstName;
                existingUser.LastName = user.LastName;
                existingUser.PhoneNumber = user.PhoneNumber;

                // Save changes to the database
                _context.SaveChanges();

                // Redirect to the profile page after saving changes
                return RedirectToAction("Index", "Profile");
            }

            // If model validation fails, return the view with validation errors
            return View(user);
        }
    }
}

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Controllers/WarehousesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class WarehousesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Warehouses
        public ActionResult Index()
        {
            return View(db.Warehouses.ToList());
        }

        // GET: Warehouses/Details/5
        public ActionResult Details(int? id)
        {

            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Warehouse warehouse = db.Warehouses.Find(id);
            var products_temp = new List<Product>();
            foreach (var prwr in warehouse.WarehouseProducts)
            {
                foreach (var product in db.Products.ToList())
                {
                    if (prwr.ProductId == product.id)
                    {
                        prwr.Product = product;
                    }
                }
            }
                
                if (warehouse == null)
                {
                    return HttpNotFound();
                }
                return View(warehouse);
            }
        

        // GET: Warehouses/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Warehouses/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,name,place")] Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                db.Warehouses.Add(warehouse);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(warehouse);
        }

        // GET: Warehouses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Warehouse warehouse = db.Warehouses.Find(id);
            if (warehouse == null)
            {
                return HttpNotFound();
            }
            return View(warehouse);
        }

        // POST: Warehouses/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,name,place")] Warehouse warehouse)
        {
            if (ModelState.IsValid)
            {
                db.Entry(warehouse).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(warehouse);
        }

        // GET: Warehouses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Warehouse warehouse = db.Warehouses.Find(id);
            if (warehouse == null)
            {
                return HttpNotFound();
            }
            return View(warehouse);
        }

        // POST: Warehouses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Warehouse warehouse = db.Warehouses.Find(id);
            db.Warehouses.Remove(warehouse);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
        // GET: Warehouses/AddExistingProduct/5
        public ActionResult AddExistingProduct(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var warehouse = db.Warehouses.Find(id);
            if (warehouse == null)
            {
                return HttpNotFound();
            }

            ViewBag.WarehouseId = id;
            ViewBag.ProductId = new SelectList(db.Products, "id", "name"); // Populate dropdown with existing products
            return View();
        }

        // POST: Warehouses/AddExistingProduct/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddExistingProduct(int id, int productId, int count)
        {
            if (count <= 0)
            {
                ModelState.AddModelError("count", "Count must be greater than zero.");
            }

            if (ModelState.IsValid)
            {
                // Check if the product is already associated with this warehouse
                var existingEntry = db.WarehouseProducts.FirstOrDefault(wp => wp.WarehouseId == id && wp.ProductId == productId);

                if (existingEntry != null)
                {
                    // Update count for existing product
                    existingEntry.Count += count;
                }
                else
                {
                    // Add new product to warehouse
                    var warehouseProduct = new WarehouseProduct
                    {
                        WarehouseId = id,
                        ProductId = productId,
                        Count = count
                    };
                    db.WarehouseProducts.Add(warehouseProduct);
                }

                db.SaveChanges();
                return RedirectToAction("Details", new { id });
            }

            ViewBag.WarehouseId = id;
            ViewBag.ProductId = new SelectList(db.Products, "id", "name", productId);
            return View();
        }
    }
}

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Warehouses/AddExistingProduct.cshtml
@model WebApplication2.Models.WarehouseProduct

@{
    ViewBag.Title = "Add Existing Product";
}

<h2>Add Product to Warehouse</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <div class="form-group">
            @Html.Label("Product", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("productId", null, "Select a Product", new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Count", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="number" name="count" class="form-control" min="1" required />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add Product" class="btn btn-primary" />
            </div>
        </div>
    </div>
}

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Warehouses/Create.cshtml
@model WebApplication2.Models.Warehouse

@{
    ViewBag.Title = "Sukurti sandėlį";
}

<h2>Sukurti sandėlį</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.place, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.place, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.place, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Sukurti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į sąrašą", "Index")
</div>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Warehouses/Delete.cshtml
@model WebApplication2.Models.Warehouse

@{
    ViewBag.Title = "Ištrinti";
}

<h2>Ištrinti sandėlį</h2>

<h3>Ar tikrai norite ištrinti šį įrašą?</h3>
<div>
    <h4>Pasirinktas sandėlis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.place)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.place)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Ištrinti" class="btn btn-default" /> |
            @Html.ActionLink("Grįžti į sąrašą", "Index")
        </div>
    }
</div>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Warehouses/Details.cshtml
@model WebApplication2.Models.Warehouse

@{
    ViewBag.Title = "Detales";
}

<h2>Detalesnė informacija</h2>

<div>
    <h4>Pasirinktas sandėlis</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.place)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.place)
        </dd>
    </dl>
</div>

<h4>Prekės sandėlyje</h4>
<table class="table">
    <thead>
        <tr>
            <th>Prekės pavadinimas</th>
            <th>Aprašymas</th>
            <th>Kaina</th>
            <th>Svoris</th>
            <th>Kiekis</th>
        </tr>
    </thead>
    <tbody>
        @if (Model.WarehouseProducts != null && Model.WarehouseProducts.Any())
        {
            foreach (var wp in Model.WarehouseProducts)
            {
                <tr>
                    <td>@wp.Product.name</td>
                    <td>@wp.Product.description</td>
                    <td>@wp.Product.price</td>
                    <td>@wp.Product.mass</td>
                    <td>@wp.Count</td>
                </tr>
            }
        }
        else
        {
            <tr>
                <td colspan="6">Šiam sandėliui nepriskirta jokių prekių.</td>
            </tr>
        }
    </tbody>
</table>

<p>
    @Html.ActionLink("Pridėti esamą prekę", "AddExistingProduct", new { id = Model.id }, new { @class = "btn btn-primary" })
</p>

<p>
    @Html.ActionLink("Redaguoti", "Edit", new { id = Model.id }, new { @class = "btn btn-secondary" }) |
    @Html.ActionLink("Grįžti į sąrašą", "Index", null, new { @class = "btn btn-secondary" })
</p>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Warehouses/Edit.cshtml
@model WebApplication2.Models.Warehouse

@{
    ViewBag.Title = "Redaguoti";
}

<h2>Redaguoti</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Sandėlis</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.place, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.place, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.place, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Išsaugoti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Grįžti į sąrašą", "Index")
</div>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Warehouses/Index.cshtml
@model IEnumerable<WebApplication2.Models.Warehouse>

@{
    ViewBag.Title = "Sandėliai";
}

<h2>Sandėliai</h2>

<p>
    @Html.ActionLink("Sukurti naują", "Create")
</p>
<table class="table">
    <tr>
        <th>
            Pavadinimas
        </th>
        <th>
            Vieta
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.place)
            </td>
            <td>
                @Html.ActionLink("Redaguoti", "Edit", new { id = item.id }) |
                @Html.ActionLink("Išsamiau", "Details", new { id = item.id }) |
                @Html.ActionLink("Ištrinti", "Delete", new { id = item.id })
            </td>
        </tr>
    }

</table>