Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Controllers/EditController.cs
using System.Linq;
using System.Web.Mvc;
using WebApplication2.Models;
using WebApplication2.Data;

namespace WebApplication2.Controllers
{
    public class EditController : Controller
    {
        private readonly DatabaseContext _context;

        public EditController()
        {
            _context = new DatabaseContext();
        }

        // GET: Edit/Index
        public ActionResult Index()
        {
            // Check if the user is logged in by checking the session
            var userId = Session["UserId"];
            if (userId == null)
            {
                return RedirectToAction("Login", "Authentication"); // Redirect to login if not logged in
            }

            var user = _context.Users.FirstOrDefault(u => u.Id == (int)userId);
            if (user == null)
            {
                return HttpNotFound(); // If no user found, return 404
            }

            return View(user); // Pass the user data to the view
        }

        // POST: Edit/Index
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(Users user)
        {
            if (ModelState.IsValid)
            {
                // Check if the user is logged in by checking the session
                var userId = Session["UserId"];
                if (userId == null)
                {
                    return RedirectToAction("Login", "Authentication"); // Redirect to login if not logged in
                }

                // Retrieve the existing user from the database
                var existingUser = _context.Users.FirstOrDefault(u => u.Id == (int)userId);
                if (existingUser == null)
                {
                    return HttpNotFound(); // If no user found, return 404
                }

                // Update the user details
                existingUser.FirstName = user.FirstName;
                existingUser.LastName = user.LastName;
                existingUser.PhoneNumber = user.PhoneNumber;

                // Save changes to the database
                _context.SaveChanges();

                // Redirect to the profile page after saving changes
                return RedirectToAction("Index", "Profile");
            }

            // If model validation fails, return the view with validation errors
            return View(user);
        }
    }
}

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Controllers/SalariesController.cs
using Mysqlx.Crud;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication2.Data;
using WebApplication2.Models;

namespace WebApplication2.Controllers
{
    public class SalariesController : Controller
    {
        private DatabaseContext db = new DatabaseContext();

        // GET: Salaries
        public ActionResult Index()
        {
            int loggedInUserId = (int)Session["UserId"];
            // Find the logged-in admin in the database
            var loggedInAdmin = db.Administrators.FirstOrDefault(a => a.Id == loggedInUserId);

            // If the logged-in admin is not found or is not a chief, restrict access
            if (loggedInAdmin == null || !loggedInAdmin.Chief)
            {
                return new HttpStatusCodeResult(HttpStatusCode.Forbidden, "Access Denied");
            }

            // Get all administrators excluding the logged-in admin
            List<Administrator> admins = db.Administrators
                .Where(a => a.Id != loggedInUserId)
                .ToList();

            // Pass the filtered administrators to the view
            ViewBag.Administrators = admins;
            return View();
        }


        // Set: Salaries/Index
        public ActionResult Payout(int adminId, string adminName, float adminSalary, float bonus)
        {
            int currentUserId = (int)Session["UserId"];
            var payout = new Salary
            {
                FkAdministratorius = currentUserId,
                bonus = bonus,
                FkAdministratorius1 = adminId,
                cost = adminSalary
            };

            db.Salaries.Add(payout);
            db.SaveChanges();

            return RedirectToAction("Index");
        }

    }
}

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Salaries/Create.cshtml
@model WebApplication2.Models.Salary

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FkAdministratorius, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FkAdministratorius, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FkAdministratorius, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FkAdministratorius1, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FkAdministratorius1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FkAdministratorius1, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bonus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bonus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bonus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Salaries/Delete.cshtml
@model WebApplication2.Models.Salary

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Salary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bonus)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Salaries/Details.cshtml
@model WebApplication2.Models.Salary

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Salary</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.cost)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.cost)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.bonus)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.bonus)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { /* id = Model.PrimaryKey */ }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Salaries/Edit.cshtml
@model WebApplication2.Models.Salary

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Salary</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.FkAdministratorius)

        @Html.HiddenFor(model => model.FkAdministratorius1)

        <div class="form-group">
            @Html.LabelFor(model => model.cost, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.cost, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.cost, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.bonus, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.bonus, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.bonus, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

Drabuziu-parduotuve-master pilnas/WebApplication2/WebApplication2/Views/Salaries/Index.cshtml
@model IEnumerable<WebApplication2.Models.Salary>

@{
    ViewBag.Title = "Apmokėti atlyginimus";
}

<h2>Apmokėti atlyginimus</h2>

<form action="@Url.Action("Payout", "Salaries")" method="post">
    @Html.AntiForgeryToken()

    <div class="form-group">
        <label for="adminId">Pasirinkti administratorių:</label>
        <select id="adminId" name="adminId" class="form-control" required onchange="updateFormFields()">
            <option value="">-- Administratorių sąrašas --</option>
            @if (ViewBag.Administrators != null)
            {
                foreach (var admin in ViewBag.Administrators)
                {
                    <option value="@admin.Id"
                            data-name="@admin.Id"
                            data-salary="@admin.Salary">
                        @admin.Id
                    </option>
                }
            }
        </select>
    </div>

    <div class="form-group">
        <label>Dabartinė alga:</label>
        <p id="currentSalary">Pasirinkite administratorių, kad pamatytumėte jo algą.</p>
    </div>

    <input type="hidden" id="adminName" name="adminName" />

    <input type="hidden" id="adminSalary" name="adminSalary" />

    <div class="form-group">
        <label for="bonus">Priskiriamas bonusas:</label>
        <input type="number" id="bonus" name="bonus" class="form-control" step="0.01" required />
    </div>

    <button type="submit" class="btn btn-primary">Apmokėti algą</button>
</form>

<script>
    function updateFormFields() {
        const dropdown = document.getElementById("adminId");
        const selectedOption = dropdown.options[dropdown.selectedIndex];

        const name = selectedOption.getAttribute("data-name");
        const salary = selectedOption.getAttribute("data-salary");

        const salaryText = document.getElementById("currentSalary");
        if (salary) {
            salaryText.textContent = `Dabartinė alga: $${parseFloat(salary).toFixed(2)}`;
        } else {
            salaryText.textContent = "Pasirinkite administratorių, kad pamatytumėte jo algą.";
        }

        document.getElementById("adminName").value = name || "";
        document.getElementById("adminSalary").value = salary || "";
    }
</script>